# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18IKNlBrTOECm1tUtRis3nn12NV_C3Ceh
"""

import gym
import numpy as np
import random
import collections
import matplotlib.pyplot as plt
import torch
import torch.nn as nn
import torch.optim as optim
from datetime import datetime

# -----------------------------
# Q-Network Architecture
# -----------------------------
class DQN(nn.Module):
    def __init__(self, state_size, action_size):
        super(DQN, self).__init__()
        self.layers = nn.Sequential(
            nn.Linear(state_size, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, action_size)
        )

    def forward(self, x):
        return self.layers(x)


# -----------------------------
# Replay Buffer
# -----------------------------
class ReplayBuffer:
    def __init__(self, max_size=100000):
        self.buffer = collections.deque(maxlen=max_size)

    def add(self, state, action, reward, next_state, done):
        self.buffer.append((state, action, reward, next_state, done))

    def sample(self, batch_size):
        batch = random.sample(self.buffer, batch_size)
        states, actions, rewards, next_states, dones = zip(*batch)
        return np.array(states), actions, rewards, np.array(next_states), dones

    def __len__(self):
        return len(self.buffer)


# -----------------------------
# DQN Agent
# -----------------------------
class Agent:
    def __init__(self, state_size, action_size):

        # Hyperparameters
        self.gamma = 0.99
        self.lr = 0.0005
        self.batch_size = 64
        self.epsilon = 1.0
        self.epsilon_min = 0.01
        self.epsilon_decay = 0.995
        self.target_update_freq = 1000

        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        # Networks
        self.q_network = DQN(state_size, action_size).to(self.device)
        self.target_network = DQN(state_size, action_size).to(self.device)
        self.target_network.load_state_dict(self.q_network.state_dict())

        self.optimizer = optim.Adam(self.q_network.parameters(), lr=self.lr)

        self.memory = ReplayBuffer()

        self.steps = 0

    def act(self, state):
        if random.random() < self.epsilon:
            return random.randrange(4)

        state = torch.FloatTensor(state).unsqueeze(0).to(self.device)
        with torch.no_grad():
            action_values = self.q_network(state)
        return torch.argmax(action_values).item()

    def train_step(self):
        if len(self.memory) < self.batch_size:
            return None

        states, actions, rewards, next_states, dones = self.memory.sample(self.batch_size)

        states = torch.FloatTensor(states).to(self.device)
        next_states = torch.FloatTensor(next_states).to(self.device)
        actions = torch.LongTensor(actions).to(self.device)
        rewards = torch.FloatTensor(rewards).to(self.device)
        dones = torch.FloatTensor(dones).to(self.device)

        # Predicted Q-values
        q_values = self.q_network(states)
        q_value = q_values.gather(1, actions.unsqueeze(1)).squeeze(1)

        # Target Q-values
        with torch.no_grad():
            next_q_values = self.target_network(next_states)
            max_next_q = torch.max(next_q_values, dim=1)[0]
            target = rewards + (1 - dones) * self.gamma * max_next_q

        loss = nn.MSELoss()(q_value, target)

        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

        # Update target network
        if self.steps % self.target_update_freq == 0:
            self.target_network.load_state_dict(self.q_network.state_dict())

        # Update epsilon
        self.epsilon = max(self.epsilon_min, self.epsilon * self.epsilon_decay)

        return loss.item()


# -----------------------------
# Training Loop
# -----------------------------
def train_dqn(episodes=300):
    env = gym.make("LunarLander-v2")
    agent = Agent(state_size=8, action_size=4)

    rewards_history = []
    loss_history = []

    for episode in range(episodes):
        state = env.reset()[0]
        total_reward = 0
        episode_loss = []

        done = False
        while not done:
            agent.steps += 1

            action = agent.act(state)
            next_state, reward, done, _, _ = env.step(action)

            agent.memory.add(state, action, reward, next_state, done)

            loss = agent.train_step()
            if loss is not None:
                episode_loss.append(loss)

            total_reward += reward
            state = next_state

        rewards_history.append(total_reward)
        loss_history.append(np.mean(episode_loss) if episode_loss else 0)

        print(
            f"Episode {episode+1}/{episodes}  "
            f"Reward: {total_reward:.2f}  "
            f"Epsilon: {agent.epsilon:.3f}"
        )

    env.close()
    return rewards_history, loss_history


# -----------------------------
# Save Learning Curves
# -----------------------------
def plot_results(rewards, losses):
    plt.figure()
    plt.plot(rewards)
    plt.xlabel("Episode")
    plt.ylabel("Reward")
    plt.title("DQN Training Reward Curve")
    plt.tight_layout()
    plt.savefig("reward_curve.png")
    plt.close()

    plt.figure()
    plt.plot(losses)
    plt.xlabel("Episode")
    plt.ylabel("Loss")
    plt.title("Training Loss Curve")
    plt.tight_layout()
    plt.savefig("loss_curve.png")
    plt.close()


# -----------------------------
# Main
# -----------------------------
if __name__ == "__main__":
    rewards, losses = train_dqn(episodes=300)
    plot_results(rewards, losses)
    print("\nTraining complete! Plots saved as reward_curve.png and loss_curve.png")